### ISSUE TITLE
scan error

### ISSUE THREAD

**Issue by Djez-Himself** [gogodr/LostArk-Market-Watcher#1]
Hello i have a problem running scans..

== New screenshoot found ==
== Scanning Be patient ==
Traceback (most recent call last):
  File "c:\Users\xxxxxxxxxx\LostArk-Market-Watcher-master\index.py", line 30, in on_created
    res = scan(event.src_path)
  File "c:\Users\xxxxxx\LostArk-Market-Watcher-master\modules\scan.py", line 224, in scan
    item = process_cropped(
  File "c:\Users\xxxxxxxxxxxxx\LostArk-Market-Watcher-master\modules\scan.py", line 133, in process_cropped
    e_text = pytesseract.image_to_string(
  File "C:\Program Files\Python310\lib\site-packages\pytesseract\pytesseract.py", line 416, in image_to_string
    return {
  File "C:\Program Files\Python310\lib\site-packages\pytesseract\pytesseract.py", line 419, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Program Files\Python310\lib\site-packages\pytesseract\pytesseract.py", line 286, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Program Files\Python310\lib\site-packages\pytesseract\pytesseract.py", line 262, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (3221225775, '')

can someone help me to thx

**Comment by gogodr** [comment]
Hello, did you clone the repo using git LFS? Some of the tesseract files are too big for regular git and that is why I am using git LFS to store and link the files.On Apr 25, 2022 2:19 AM, Djez-Himself ***@***.***> wrote:
Hello i have a problem running scans..
== New screenshoot found ==
== Scanning Be patient ==
Traceback (most recent call last):
File "c:\Users\xxxxxxxxxx\LostArk-Market-Watcher-master\index.py", line 30, in on_created
res = scan(event.src_path)
File "c:\Users\xxxxxx\LostArk-Market-Watcher-master\modules\scan.py", line 224, in scan
item = process_cropped(
File "c:\Users\xxxxxxxxxxxxx\LostArk-Market-Watcher-master\modules\scan.py", line 133, in process_cropped
e_text = pytesseract.image_to_string(
File "C:\Program Files\Python310\lib\site-packages\pytesseract\pytesseract.py", line 416, in image_to_string
return {
File "C:\Program Files\Python310\lib\site-packages\pytesseract\pytesseract.py", line 419, in 
Output.STRING: lambda: run_and_get_output(*args),
File "C:\Program Files\Python310\lib\site-packages\pytesseract\pytesseract.py", line 286, in run_and_get_output
run_tesseract(**kwargs)
File "C:\Program Files\Python310\lib\site-packages\pytesseract\pytesseract.py", line 262, in run_tesseract
raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (3221225775, '')
can someone help me to thx

**Comment by Djez-Himself** [comment]
Non i didn't clone your repo, i tried to install everything alone. i'm noob dev i'm tring to understand how it works.
i'll try the LTS ;)

Thx for the work !!

**Comment by Djez-Himself** [comment]
It works with Git LTS bro, thx a lot !

== New screenshoot found ==
== Scanning ==
Rarity - 0: 1
['Shy Wild Flower\n[Sold in bundles of 10 units]\n', '2.6\n', '2\n', '2\n', '1\n', 1]
Rarity - 1: 1
['Fresh Mushroom\n[Sold in bundles of 10 units)\n', '1.6\n', '2\n', '2\n', '10.297\n', 1]
Rarity - 2: 2
['Bright Wild Flower\n[Sold in bundles of 10 units]\n', '3.6\n', '3\n', '3\n', '43\n', 2]
Rarity - 3: 2
['Exquisite Mushroom\n[Sold in bundles of 10 units]\n', '3.0\n', '3\n', '3\n', '125\n', 2]
Rarity - 4: 0
['Crude Mushroom\n[Sold in bundles of 100 units]\n', '5.3\n', '5\n', '4\n', '1\n', 0]
Rarity - 5: 0
['Wild Flower\n[Sold in bundles of 100 units]\n', '32.7\n', '29\n', '29\n', '12\n', 0]

Thx a lot, if you need help for something i can work for you, i'm total noob but i try my best.

**Comment by gogodr** [comment]
Awesome, if you have any question feel free to hit me up on reddit or open another issue ✌
